version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      args:
        - NODE_ENV=production
    container_name: master-project-app
    environment:
      USE_HTTPS: ${USE_HTTPS}
      NO_CONSOLE_LOGGING: ${NO_CONSOLE_LOGGING}
      NO_FILE_LOGGING: ${NO_FILE_LOGGING}
      BACKEND_PORT: ${BACKEND_PORT}
      API_KEY_DEV: ${API_KEY_DEV}
      WORKER_ACTIVE: ${WORKER_ACTIVE}
      WORKER_DELAY: ${WORKER_DELAY}
      WORKER_RUN_FILE_PATH: ${WORKER_RUN_FILE_PATH}
      CONFIG_PATH: ${CONFIG_PATH}
      SIMULATION_PORT: ${SIMULATION_PORT}
      URL_METHANATION_001: sim_001
      URL_METHANATION_002: sim_001
      URL_METHANATION_003: sim_001
      URL_METHANATION_004: sim_001
      URL_METHANATION_005: sim_001
    networks:
      - backend
    ports:
      - 8080:${BACKEND_PORT}
    command: node ./src/index.js
    depends_on:
      - sim_001

  sim_001:
    build:
      context: .
      dockerfile: ./packages/simulation/Dockerfile
      args:
        - ENV=production
    container_name: master-project-sim_001
    restart: on-failure:3
    environment:
      SIMULATION_PORT: ${SIMULATION_PORT}
    networks:
      - backend
    ports:
      - 3001:${SIMULATION_PORT}
    command: python3 /app/simulations/methanation/Methanation_local_smart/start.py

networks:
  backend:
