version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
      args:
        - NODE_ENV=production
    container_name: master-project-app
    environment:
      USE_HTTPS: ${USE_HTTPS}
      BACKEND_PORT: ${BACKEND_PORT}
      API_KEY_DEV: ${API_KEY_DEV}
      WORKER_ACTIVE: ${WORKER_ACTIVE}
      WORKER_DELAY: ${WORKER_DELAY}
      WORKER_RUN_FILE_PATH: ${WORKER_RUN_FILE_PATH}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SIMULATION_URL: sim_001
      SIMULATION_PORT: ${SIMULATION_PORT}
      METHANATION_001_URL: sim_001
      METHANATION_002_URL: sim_001
      METHANATION_003_URL: sim_001
      METHANATION_004_URL: sim_001
      METHANATION_005_URL: sim_001
    networks:
      - backend
    ports:
      - 8080:${BACKEND_PORT}
    command: node ./src/index.js
    depends_on:
      - sim_001
      - cache

  sim_001:
    build:
      context: .
      dockerfile: ./packages/simulation/Dockerfile
      args:
        - ENV=production
    container_name: master-project-sim_001
    restart: on-failure:3
    environment:
      SIMULATION_PORT: ${SIMULATION_PORT}
    networks:
      - backend
    ports:
      - 3001:${SIMULATION_PORT}
    command: python3 /app/simulations/methanation/Methanation_local_smart/start.py

  cache:
    image: redis:7.2
    container_name: master-project-cache
    restart: always
    networks:
      - backend
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache_data:/data

networks:
  backend:

volumes:
  cache_data:
